version: '3'
services:
  sqlserver:
    image: "sqlserver:latest" # Source: "mcr.microsoft.com/mssql/server"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "${SA_PASSWORD}"
        ACCEPT_EULA: "Y"
        MSSQL_TCP_PORT: "1433"
